version: '3'

services:
  app:
    image: oven/bun:latest
    container_name: bun-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: ["bun", "start"]
    environment:
      NODE_ENV: development
