version: '3'

services:
  app:
    build:
      context: .
      dockerfile: DockerfileServer
    container_name: t1-calendar-server
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: ["bun", "start"]
    environment:
      NODE_ENV: production

