version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: t1-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: ["bun", "start"]
    environment:
      NODE_ENV: production

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: t1-app-dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: ["bun", "dev"]
    environment:
      NODE_ENV: development
