version: '3'

services:
  t1-calendar:
    image: oven/bun:1.2.0
    container_name: t1-calendar
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: ["sh", "-c", "bun install && bun run dev"]
    environment:
      NODE_ENV: development
